<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="QA-HIMANSHU-RANJAN" failures="3" tests="38" name="Default test" time="162.526" errors="0" timestamp="2025-04-02T09:48:02 IST">
  <testcase classname="UAT_SIP2.Dealer_User_Login" name="PopuPhandle" time="6.662"/>
  <testcase classname="UAT_SIP2.Dealer_User_Login" name="Dealer_User_Login1" time="4.261"/>
  <testcase classname="UAT_SIP2.Dealer_User_Login" name="Click_On_SIP" time="4.886"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Additional_Fillter_To_Clear_Data" time="5.375"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer_Page" time="0.524"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Call_Dispostion" time="0.133"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Verify_Booking_Feedback" time="10.623">
    <failure type="org.openqa.selenium.TimeoutException" message="Expected condition failed: waiting for visibility of element located by By.xpath: (//*[text()=&amp;quot; Yes &amp;quot;])[2] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: &amp;apos;4.21.0&amp;apos;, revision: &amp;apos;79ed462ef4&amp;apos;
System info: os.name: &amp;apos;Windows 11&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.6&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 134.0.6998.178, chrome: {chromedriverVersion: 134.0.6998.165 (fd886e2cb29..., userDataDir: C:\Users\Admin\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50376}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50376/devtoo..., se:cdpVersion: 134.0.6998.178, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 2ed5427b0005732a972a1b244f40d434">
      <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: (//*[text()=" Yes "])[2] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.21.0', revision: '79ed462ef4'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 134.0.6998.178, chrome: {chromedriverVersion: 134.0.6998.165 (fd886e2cb29..., userDataDir: C:\Users\Admin\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:50376}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:50376/devtoo..., se:cdpVersion: 134.0.6998.178, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 2ed5427b0005732a972a1b244f40d434
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at UAT_SIP2.Call_Dispostion.clickElementWithDelay(Call_Dispostion.java:537)
at UAT_SIP2.Call_Dispostion.Select_Option_Booking_Feedback(Call_Dispostion.java:524)
at UAT_SIP2.Call_Dispostion.Verify_Booking_Feedback(Call_Dispostion.java:91)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Verify_Booking_Feedback -->
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Booking_Feedback_SuccessMessage" time="10.145">
    <failure type="java.lang.AssertionError" message="After Punching Booking_Feedback, success message is not Display ">
      <![CDATA[java.lang.AssertionError: After Punching Booking_Feedback, success message is not Display 
at org.testng.Assert.fail(Assert.java:99)
at UAT_SIP2.Call_Dispostion.Booking_Feedback_SuccessMessage(Call_Dispostion.java:100)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Booking_Feedback_SuccessMessage -->
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer1" time="11.193">
    <failure type="java.lang.AssertionError" message="Additional Fillter_Button could not be clickable.">
      <![CDATA[java.lang.AssertionError: Additional Fillter_Button could not be clickable.
at org.testng.Assert.fail(Assert.java:99)
at UAT_SIP2.Call_Dispostion.Click_On_CustomerPage_And_FillterButton(Call_Dispostion.java:582)
at UAT_SIP2.Call_Dispostion.Click_On_Customer1(Call_Dispostion.java:107)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Click_On_Customer1 -->
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Verify_Call_Me_Later" time="6.182"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Call_Me_Later_SuccessMessage" time="0.279"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer2" time="7.997"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Verify_WrongNumber" time="1.968"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="WrongNumber_SuccessMessage" time="0.405"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer3" time="7.927"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Verify_VehicleDelivery_Visit" time="5.312"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="VehicleDelivery_Visit_SuccessMessage" time="0.307"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer4" time="7.889"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="ClickOn_NotPickedUp" time="1.869"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Verify_NotPickedUp" time="3.984"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="NotPickedUp_SuccessMessage" time="0.28"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer5" time="7.947"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="ClickOn_NumberBusy" time="1.905"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Verify_NumberBusy" time="4.008"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="NumberBusy_SuccessMessage" time="0.291"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer6" time="7.894"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="ClickOn_NotRechable" time="1.892"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Verify_NotRechable" time="4.029"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="NotRechable_SuccessMessage" time="0.309"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer7" time="7.912"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="ClickOn_SwitchedOff" time="1.887"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Verify_SwitchedOff" time="4.005"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="SwitchedOff_SuccessMessage" time="0.428"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer8" time="7.941"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="ClickOn_Invalid_Numbers" time="1.923"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Verify_Invalid_Numbers" time="1.766"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Invalid_Numbers_SuccessMessage" time="0.297"/>
  <testcase classname="UAT_SIP2.Call_Dispostion" name="Click_On_Customer9" time="7.906"/>
</testsuite> <!-- Default test -->
