<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7SBKKJ1" failures="3" tests="13" name="DEMOAPI_Testing.Api_TestingPROD" time="5.840" errors="0" timestamp="2025-03-03T10:16:06 IST" skipped="0">
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="EmployeeDataByMspin" time="1.628">
    <failure message="Expected status code 200 OK, but received: 405 (Unknown Status) expected [200] but found [405]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 200 OK, but received: 405 (Unknown Status) expected [200] but found [405]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at DEMOAPI_Testing.Api_TestingPROD.StatusCode(Api_TestingPROD.java:344)
at DEMOAPI_Testing.Api_TestingPROD.EmployeeDataByMspin(Api_TestingPROD.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- EmployeeDataByMspin -->
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="getColumnNames" time="0.372"/>
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="getCustomerTAGList" time="0.301"/>
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="getBookingList" time="0.542"/>
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="getSubTabs" time="0.284"/>
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="UserLoginData" time="0.354"/>
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="UpdateVehicleStatus" time="0.313"/>
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="Update_CustomerExpected_Date" time="0.319"/>
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="UpdateCustomerTAG" time="0.323">
    <failure message="Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at DEMOAPI_Testing.Api_TestingPROD.StatusCode(Api_TestingPROD.java:344)
at DEMOAPI_Testing.Api_TestingPROD.UpdateCustomerTAG(Api_TestingPROD.java:250)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- UpdateCustomerTAG -->
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="getReceiptDetails" time="0.329"/>
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="getLoanStatus" time="0.449">
    <failure message="Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected status code 200 OK, but received: 500 (Internal Server Error) expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at DEMOAPI_Testing.Api_TestingPROD.StatusCode(Api_TestingPROD.java:344)
at DEMOAPI_Testing.Api_TestingPROD.getLoanStatus(Api_TestingPROD.java:294)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getLoanStatus -->
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="getDocumentList" time="0.302"/>
  <system-out/>
  <testcase classname="DEMOAPI_Testing.Api_TestingPROD" name="getCustomerSVOC" time="0.324"/>
  <system-out/>
</testsuite> <!-- DEMOAPI_Testing.Api_TestingPROD -->
